config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :set_question, only: %i[update show destroy edit]

    def create
      question = Question.create(question_params)
  
      redirect_to question_path(question), notice: 'You question created!'
    end
  
    def update
      @question.update(question_params)    
  
      redirect_to question_path(@question), notice: 'Saved question!'
    end
  
    def destroy
      @question.destroy
  
      redirect_to questions_path, notice: 'Question deleted!'
    end
  
    def show
    end
  
    def index
      @question = Question.new
      @questions = Question.all
    end
  
    def new
      @question = Question.new
    end
  
    def edit
  
    end
  
    private
    
    def question_params
      question_params = params.require(:question).permit(:body, :user_id)
    end
  
    def set_question
      @question = Question.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
	<p><%= form.label :body, 'Text question' %></p>
	<p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

	<p class="mt"><%= form.label :user_id %></p>
	<p><%= form.text_field :user_id, class: 'form-text-field' %></p>

	<p class="mt"><%= form.submit 'Save', class: 'button button-main' %></p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm">
	<%= question.body %>
</div>

<div class="text-sm question-footer">
		<div class="text-grey">
			<%= l(question.created_at, format: :short) %>
	</div>

	<div>
 		<%= link_to fa_icon('pencil'), edit_question_path(question), 
		 title: 'Edit question' %>
		<%= button_to fa_icon('trash-o'), question_path(question),
		 method: :delete, title: 'Delete question' %>
	</div>
</div>

app/views/questions/edit.html.erb
<div class="container">
	<h2 class="title-lg mb">Edit question <%= @question.id %></h2>

	<%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <p class="mt">
    <%= link_to "Create new question", new_question_path, class: 'button button-main' %>
  </p>

  <p class="mt">
    <%= render 'form', question: @question %>
  </p>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">All Questions</h2>
</div>

  <% @questions.each do |question| %>
    <div class="mt-sm container">
      <%= render question %>
    </div>
  <% end %>

app/views/questions/new.html.erb
<div class="container">
	<h2 class="title-lg mb">New Question</h2>

	<%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Питання <%= @question.id %></h2>

  <%= render 'question', question: @question %>

  <p class="mt"><%= link_to "All questions", questions_path %></p>
</div>